### ISSUE TITLE
License violation?

### ISSUE THREAD

**Issue by sdebruyn** [Montreal-Analytics/dbt-gloss-deprecated#17]
The license in this project indicates that the project is copyrighted by Montreal Analytics in 2022. However, most of the code is coming from https://github.com/offbi/pre-commit-dbt

That project has an MIT license which contains the following note:

> The above copyright notice and this permission notice shall be included in all
> copies or substantial portions of the Software.

Shouldn't this license then also include the name of the original project and its copyright?

> Copyright (c) 2020 Offbi

**Comment by MartinGuindon** [comment]
Hello @sdebruyn ,

Apologies for the delay in answering to this issue, and for bringing this to light. It was not our intention to violate the license. This was overlooked when we did a search & replace on the codebase to change references to the repo, hence why its indicated "Montreal-Analytics" with a dash (as per our organization name on GitHub) and not "Montreal Analytics Inc.".

Since we took over, the following credits had been added on the README:
> This software is a fork of [pre-commit-dbt](https://github.com/offbi/pre-commit-dbt/). We created this fork since the last release of pre-commit-dbt is dated April 2021 and had many unresolved issues with more recent versions of dbt. As of September 2022, dbt-gloss is supported, but not warrantied by Montreal Analytics. Issues and feature requests can be reported via https://github.com/Montreal-Analytics/dbt-gloss/issues, which will be regularly monitored and prioritized by Montreal Analytics, a preferred dbt consulting partner. Major thanks to Radek Tomsej who originally created this tool.

Having said this, this repository will soon be archived, as we are uniting forces with Datacoves to co-maintain the original repository, now renamed and moved at [`https://github.com/dbt-checkpoint/dbt-checkpoint`.](https://github.com/dbt-checkpoint/dbt-checkpoint), where we'll bring in our improvements and changes.
